image: mwienk/docker-git-ftp
deploy_all:
  stage: deploy
  script:
    - git config git-ftp.url "ftp://ftp.sowlab.xyz/credit-cloud"
    - git config git-ftp.password "FfU~Ha2~R;V]"
    - git config git-ftp.user "sravan.kumar@sowlab.xyz"
    - git ftp init
    - git ftp push
  only:
    - main