on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.sowlab.xyz
        username: sravan.kumar@sowlab.xyz
        password: FfU~Ha2~R;V]
        local-dir: ../../ 
        server-dir: home/sowlaouw/sowlab.xyz/demo/credit-cloud/  
